/**
 * Maps manifest icon string IDs to React icon components.
 *
 * Manifest JSON files reference icons by string ID (e.g. "SlackIcon").
 * This module resolves those strings to the actual component from
 * `@/components/icons`.
 */

import { createElement } from 'react'
import type { SVGProps } from 'react'
import type { BlockIcon } from '@/blocks/types'
import {
  A2AIcon,
  AgentIcon,
  AhrefsIcon,
  AirweaveIcon,
  AirtableIcon,
  ApifyIcon,
  ApolloIcon,
  ApiIcon,
  ArxivIcon,
  AsanaIcon,
  AzureIcon,
  BedrockIcon,
  BoxCompanyIcon,
  BrainIcon,
  BrowserUseIcon,
  CalComIcon,
  CalendlyIcon,
  ChartBarIcon,
  ChatTriggerIcon,
  CirclebackIcon,
  ClayIcon,
  ClerkIcon,
  CodeIcon,
  ConditionalIcon,
  ConfluenceIcon,
  ConnectIcon,
  CrunchbaseIcon,
  CursorIcon,
  DatadogIcon,
  DiscordIcon,
  DocumentIcon,
  DropboxIcon,
  DsPyIcon,
  DuckDuckGoIcon,
  DynamoDBIcon,
  ElasticsearchIcon,
  ElevenLabsIcon,
  EnrichSoIcon,
  ExaAIIcon,
  EyeIcon,
  FirecrawlIcon,
  FirefliesIcon,
  GeminiIcon,
  GithubIcon,
  GitLabIcon,
  GmailIcon,
  GoogleBooksIcon,
  GoogleCalendarIcon,
  GoogleDocsIcon,
  GoogleDriveIcon,
  GoogleFormsIcon,
  GoogleGroupsIcon,
  GoogleIcon,
  GoogleMapsIcon,
  GoogleSheetsIcon,
  GoogleSlidesIcon,
  GoogleVaultIcon,
  GrafanaIcon,
  GrainIcon,
  GreptileIcon,
  HubspotIcon,
  HuggingFaceIcon,
  HumanInTheLoopIcon,
  HunterIOIcon,
  ImageIcon,
  IncidentioIcon,
  InputIcon,
  InputTriggerIcon,
  IntercomIcon,
  JinaAIIcon,
  JiraIcon,
  JiraServiceManagementIcon,
  KalshiIcon,
  LangsmithIcon,
  LemlistIcon,
  LinearIcon,
  LinkedInIcon,
  LinkupIcon,
  MailchimpIcon,
  MailgunIcon,
  MailIcon,
  MailServerIcon,
  ManualTriggerIcon,
  McpIcon,
  Mem0Icon,
  MicrosoftExcelIcon,
  MicrosoftIcon,
  MicrosoftOneDriveIcon,
  MicrosoftPlannerIcon,
  MicrosoftSharepointIcon,
  MicrosoftTeamsIcon,
  MistralIcon,
  MongoDBIcon,
  MySQLIcon,
  Neo4jIcon,
  NoteIcon,
  NotionIcon,
  OnePasswordIcon,
  OpenAIIcon,
  OpenRouterIcon,
  OutlookIcon,
  PackageSearchIcon,
  ParallelIcon,
  PerplexityIcon,
  PineconeIcon,
  PipedriveIcon,
  PolymarketIcon,
  PosthogIcon,
  PostgresIcon,
  PulseIcon,
  QdrantIcon,
  RDSIcon,
  RedditIcon,
  ReductoIcon,
  ResendIcon,
  ResponseIcon,
  RssIcon,
  S3Icon,
  SalesforceIcon,
  ScheduleIcon,
  SearchIcon,
  SendgridIcon,
  SentryIcon,
  SerperIcon,
  ServerIcon,
  ServiceNowIcon,
  SftpIcon,
  ShieldCheckIcon,
  ShopifyIcon,
  SimilarwebIcon,
  SlackIcon,
  SmtpIcon,
  SpotifyIcon,
  SQSIcon,
  SshIcon,
  SSHIcon,
  StagehandIcon,
  StartIcon,
  STTIcon,
  StripeIcon,
  SupabaseIcon,
  TavilyIcon,
  TelegramIcon,
  TextractIcon,
  TinybirdIcon,
  TranslateIcon,
  TrelloIcon,
  TTSIcon,
  TwilioIcon,
  TypeformIcon,
  VariableIcon,
  VideoIcon,
  VllmIcon,
  WaitIcon,
  WealthboxIcon,
  WebflowIcon,
  WebhookIcon,
  WhatsAppIcon,
  WikipediaIcon,
  WordpressIcon,
  WorkflowIcon,
  xAIIcon,
  xIcon,
  YouTubeIcon,
  ZendeskIcon,
  ZepIcon,
  ZoomIcon,
} from '@/components/icons'

/**
 * Map of icon string IDs to React icon components.
 * Manifest JSON files use these string IDs to reference icons.
 */
const ICON_MAP: Record<string, BlockIcon> = {
  A2AIcon,
  AgentIcon,
  AhrefsIcon,
  AirweaveIcon,
  AirtableIcon,
  ApifyIcon,
  ApolloIcon,
  ApiIcon,
  ArxivIcon,
  AsanaIcon,
  AzureIcon,
  BedrockIcon,
  BoxCompanyIcon,
  BrainIcon,
  BrowserUseIcon,
  CalComIcon,
  CalendlyIcon,
  ChartBarIcon,
  ChatTriggerIcon,
  CirclebackIcon,
  ClayIcon,
  ClerkIcon,
  CodeIcon,
  ConditionalIcon,
  ConfluenceIcon,
  ConnectIcon,
  CrunchbaseIcon,
  CursorIcon,
  DatadogIcon,
  DiscordIcon,
  DocumentIcon,
  DropboxIcon,
  DsPyIcon,
  DuckDuckGoIcon,
  DynamoDBIcon,
  ElasticsearchIcon,
  ElevenLabsIcon,
  EnrichSoIcon,
  ExaAIIcon,
  EyeIcon,
  FirecrawlIcon,
  FirefliesIcon,
  GeminiIcon,
  GithubIcon,
  GitLabIcon,
  GmailIcon,
  GoogleBooksIcon,
  GoogleCalendarIcon,
  GoogleDocsIcon,
  GoogleDriveIcon,
  GoogleFormsIcon,
  GoogleGroupsIcon,
  GoogleIcon,
  GoogleMapsIcon,
  GoogleSheetsIcon,
  GoogleSlidesIcon,
  GoogleVaultIcon,
  GrafanaIcon,
  GrainIcon,
  GreptileIcon,
  HubspotIcon,
  HuggingFaceIcon,
  HumanInTheLoopIcon,
  HunterIOIcon,
  HunterIcon: HunterIOIcon,
  ImageIcon,
  IncidentioIcon,
  InputIcon,
  InputTriggerIcon,
  IntercomIcon,
  JinaAIIcon,
  JinaIcon: JinaAIIcon,
  JiraIcon,
  JiraServiceManagementIcon,
  KalshiIcon,
  LangsmithIcon,
  LemlistIcon,
  LinearIcon,
  LinkedInIcon,
  LinkupIcon,
  MailchimpIcon,
  MailgunIcon,
  MailIcon,
  MailServerIcon,
  ManualTriggerIcon,
  McpIcon,
  Mem0Icon,
  MicrosoftExcelIcon,
  MicrosoftIcon,
  MicrosoftOneDriveIcon,
  MicrosoftPlannerIcon,
  MicrosoftSharepointIcon,
  MicrosoftTeamsIcon,
  MistralIcon,
  MongoDBIcon,
  MySQLIcon,
  Neo4jIcon,
  NoteIcon,
  NotionIcon,
  OnePasswordIcon,
  OpenAIIcon,
  OpenRouterIcon,
  OutlookIcon,
  PackageSearchIcon,
  ParallelIcon,
  PerplexityIcon,
  PineconeIcon,
  PipedriveIcon,
  PolymarketIcon,
  PosthogIcon,
  PostgresIcon,
  PulseIcon,
  QdrantIcon,
  RDSIcon,
  RedditIcon,
  ReductoIcon,
  ResendIcon,
  ResponseIcon,
  RssIcon,
  S3Icon,
  SalesforceIcon,
  ScheduleIcon,
  SearchIcon,
  SendgridIcon,
  SentryIcon,
  SerperIcon,
  ServerIcon,
  ServiceNowIcon,
  SftpIcon,
  ShieldCheckIcon,
  ShopifyIcon,
  SimilarwebIcon,
  SlackIcon,
  SmtpIcon,
  SpotifyIcon,
  SQSIcon,
  SshIcon,
  SSHIcon,
  StagehandIcon,
  StartIcon,
  STTIcon,
  StripeIcon,
  SupabaseIcon,
  TavilyIcon,
  TelegramIcon,
  TextractIcon,
  TinybirdIcon,
  TranslateIcon,
  TrelloIcon,
  TTSIcon,
  TwilioIcon,
  TypeformIcon,
  VariableIcon,
  VideoIcon,
  VllmIcon,
  WaitIcon,
  WealthboxIcon,
  WebflowIcon,
  WebhookIcon,
  WhatsAppIcon,
  WikipediaIcon,
  WordpressIcon,
  WorkflowIcon,
  xAIIcon,
  xIcon,
  YouTubeIcon,
  ZendeskIcon,
  ZepIcon,
  ZoomIcon,
}

/**
 * Cache of inline SVG components created from marketplace SVG strings.
 * Prevents creating new component references on every call.
 */
const inlineSvgCache = new Map<string, BlockIcon>()

/**
 * Creates a React component from a raw SVG string.
 * The component renders the SVG inline using dangerouslySetInnerHTML.
 */
function createInlineSvgIcon(svgString: string): BlockIcon {
  const cached = inlineSvgCache.get(svgString)
  if (cached) return cached

  const InlineSvgIcon = ((props: SVGProps<SVGSVGElement>) => {
    const { width = 24, height = 24, className, style } = props
    return createElement('span', {
      className,
      style: { display: 'inline-flex', width, height, ...(style as Record<string, unknown>) },
      dangerouslySetInnerHTML: { __html: svgString },
    })
  }) as BlockIcon
  inlineSvgCache.set(svgString, InlineSvgIcon)
  return InlineSvgIcon
}

/**
 * Resolves an icon string ID from a manifest to a React component.
 * Checks local ICON_MAP first, then falls back to inline SVG if provided.
 * Returns a fallback icon if neither is available.
 */
export function resolveIcon(iconId: string, iconSvg?: string): BlockIcon {
  // 1. Check local icon components
  if (ICON_MAP[iconId]) return ICON_MAP[iconId]

  // 2. Use inline SVG from marketplace if available
  if (iconSvg) return createInlineSvgIcon(iconSvg)

  // 3. Fallback
  return SearchIcon
}

/**
 * Checks if an icon ID is available in the icon map.
 */
export function hasIcon(iconId: string): boolean {
  return iconId in ICON_MAP
}
